name: Deploy to Server

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rsync
      run: sudo apt-get install -y rsync

    - name: Deploy to FOSSBilling server
      run: |
        ssh -o StrictHostKeyChecking=no hamza@192.168.129.101 << 'EOF'
          cd /var/www/fossbilling/modules/wp-integration
          rsync -avz Fossbilling-integration/ /var/www/fossbilling/modules/wp-integration/
          composer install
        EOF

    - name: Deploy to WordPress server
      run: |
        ssh -o StrictHostKeyChecking=no hamza@192.168.129.101 << 'EOF'
          cd /var/www/html/wp-content/plugins/fossbilling-integration
          rsync -avz wp-integration/ /var/www/html/wp-content/plugins/fossbilling-integration/
          composer install
        EOF
