name: Deploy to Server

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to FOSSBilling server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" Fossbilling-integration/ hamza@192.168.129.101:/var/www/fossbilling/modules/wp-integration/
        ssh hamza@192.168.129.101 'cd /var/www/fossbilling/modules/wp-integration && composer install'

    - name: Deploy to WordPress server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" wp-integration/ hamza@192.168.129.101:/var/www/html/wp-content/plugins/fossbilling-integration/
        ssh hamza@192.168.129.101 'cd /var/www/html/wp-content/plugins/fossbilling-integration && composer install'
