name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push FOSSBilling image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: fossbilling/fossbilling:latest

    - name: Build and push WordPress image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: yourdockerhubusername/wordpress:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Server
      run: |
        ssh hamza@yourserver 'cd /path/to/your/docker-compose && docker-compose pull && docker-compose up -d'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DOCKER_HOST: ssh://hamza@yourserver
