name: Deploy to Server

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 192.168.129.68 >> ~/.ssh/known_hosts

    - name: Install rsync
      run: sudo apt-get install -y rsync

    - name: Build project (optional)
      run: |
        # Placez ici vos commandes de build si nécessaire
        echo "Build completed"

    - name: Deploy to Server
      run: |
        rsync -avz --exclude='.git' --exclude='node_modules' ./ hamza@192.168.129.68:/var/www/html/wordpress/wp-content/plugins/fossbilling-integration/
        rsync -avz --exclude='.git' --exclude='node_modules' ./ hamza@192.168.129.68:/var/www/html/fossbilling/modules/wp-integration/
